apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-processor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-processor
  template:
    metadata:
      labels:
        app: payment-processor
    spec:
      hostname: payment-processed-at-private-cluster  # Add the hostname here
      containers:
        - name: payment-processor
          image: quay.io/redhatintegration/patient-portal-payment-processor:devnation
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: payment-processor
spec:
  selector:
    app: payment-processor
  ports:
    - port: 8080
